name: Cache Demo Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          ~/.cache
          node_modules
          .venv
        key: cache-3969eaf-${{ hashFiles('**/package-lock.json', '**/requirements.txt') }}
        restore-keys: |
          cache-3969eaf-
    
    - name: prime-cache-3969eaf
      id: prime-cache
      run: |
        if [ "${{ steps.cache-deps.outputs.cache-hit }}" == 'true' ]; then
          echo "✅ Cache hit - dependencies restored from cache"
          echo "result=cache-hit" >> $GITHUB_OUTPUT
        else
          echo "🔄 Cache miss - will prime the cache"
          # Simulate installing dependencies
          mkdir -p ~/.cache/prime-cache
          echo "Primed on $(date)" > ~/.cache/prime-cache/timestamp
          echo "Cache key: cache-3969eaf" >> ~/.cache/prime-cache/info
          echo "result=cache-miss" >> $GITHUB_OUTPUT
        fi
    
    - name: Install dependencies (simulated)
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        echo "Installing dependencies..."
        # Simulate time-consuming dependency installation
        sleep 10
        echo "Dependencies installed successfully!"
    
    - name: Run tests
      run: |
        echo "Running tests with cached dependencies..."
        echo "Cache status: ${{ steps.prime-cache.outputs.result }}"
